<h1><center>CREATING DATAFRAMES & ANALYZING PROPERTIES</h1>


<h4>To create Pandas DataFrames using NumPy arrays, CSV/Excel files and analyze the various properties of the DataFrames for real world structured data analysis.</h4>

<h2> 1: Install and Import the Libraries using commands: </h2>

<h5> pip install numpy</h5>
<h5>pip install pandas</h5>

In [2]:
# importing NumPy & Pandas
import numpy as np
import pandas as pd

<h2> 2: Create a 2-D array</h2>

In [3]:
# Considering a 4 weeks bike sales data in three different branches 
# rows --> branches, columns --> weeks

sales_thrilokya_128 = np.array([[160, 220, 140, 100],
                 [140, 260, 110, 290],
                [190, 320, 280, 250]])

In [4]:
# sales array properties

sales_thrilokya_128.shape, sales_thrilokya_128.ndim

((3, 4), 2)

<h2> 3: Converting the created 2-D array into DataFrame using Pandas</h2>

In [5]:
df = pd.DataFrame(sales_thrilokya_128) 
df

     0    1    2    3
0  160  220  140  100
1  140  260  110  290
2  190  320  280  250

In [6]:
# Creating the Index & Columns for the DataFrame 
# Index --> Branches, Columns --> Weeks
df_index = ['Branch_1', 'Branch_2', 'Branch_3'] 
df_columns = ['Week_1', 'Week_2', 'Week_3', 'Week_4']

In [7]:
# Assigning the index & columns to the dataframe
df = pd.DataFrame(data = sales_thrilokya_128, index = df_index, columns = df_columns)

In [8]:
df

          Week_1  Week_2  Week_3  Week_4
Branch_1     160     220     140     100
Branch_2     140     260     110     290
Branch_3     190     320     280     250

<h2>4:Add Rows and Columns</h2>

In [9]:
# Add Branch_4 (Row)
branch_4 = pd.DataFrame({
    'Week_1': [195],
    'Week_2': [265],
    'Week_3': [175], 
    'Week_4': [290], 
    'Week_5': [245] ,
    'Week_6': [290]
}, index=['Branch_4']) 
df = pd.concat([df, branch_4])
df

          Week_1  Week_2  Week_3  Week_4  Week_5  Week_6
Branch_1     160     220     140     100     NaN     NaN
Branch_2     140     260     110     290     NaN     NaN
Branch_3     190     320     280     250     NaN     NaN
Branch_4     195     265     175     290   245.0   290.0

<h2>5: Creating a DataFrame with Existing CSV/EXCEL File</h2>

In [10]:
import pandas as pd

stu_df = pd.read_csv("students_data.csv")
stu_df

,Name,Age,City,Math Marks,Science Marks,English Marks,History Marks,Geography Marks,Computer Marks,Attendance,Hobbies
0,Aarav_001,19,Hyderabad,98,88,74,67,80,98,74.68,Reading
1,Aadhya_002,20,Vijayawada,70,70,83,95,99,83,70.62,Sports
2,Vihaan_003,18,Visakhapatnam,61,83,89,97,61,80,79.13,Music
3,Anaya_004,23,Rajahmundry,81,84,86,87,75,74,72.72,Drawing
4,Arjun_005,19,Kakinada,62,96,66,80,68,98,98.47,Coding
...,...,...,...,...,...,...,...,...,...,...,...
295,Navya_296,18,Chennai,62,95,63,73,100,100,85.91,Traveling
296,Ayaan_297,19,Pune,69,80,95,71,86,99,88.06,Photography
297,Sneha_298,20,Mumbai,91,90,75,91,91,93,71.31,Gaming
298,Manav_299,20,Delhi,76,99,77,68,84,99,86.50,Dancing
299,Pooja_300,20,Kolkata,84,81,89,79,80,91,96.61,Gardening

<h2>Step 6: Analyze the Important Properties of the DataFrames</h2>

In [11]:
# To view first 5 data points 
stu_df.head()

,Name,Age,City,Math Marks,Science Marks,English Marks,History Marks,Geography Marks,Computer Marks,Attendance,Hobbies
0,Aarav_001,19,Hyderabad,98,88,74,67,80,98,74.68,Reading
1,Aadhya_002,20,Vijayawada,70,70,83,95,99,83,70.62,Sports
2,Vihaan_003,18,Visakhapatnam,61,83,89,97,61,80,79.13,Music
3,Anaya_004,23,Rajahmundry,81,84,86,87,75,74,72.72,Drawing
4,Arjun_005,19,Kakinada,62,96,66,80,68,98,98.47,Coding

In [12]:
# Shape of the DataFrame 
stu_df.shape

(300, 11)

In [13]:
# Index Range of the DataFrame
stu_df.index

RangeIndex(start=0, stop=300, step=1)

In [14]:
# Data Types in the DataFrame
stu_df.dtypes

Name                object
Age                  int64
City                object
Math Marks           int64
Science Marks        int64
English Marks        int64
History Marks        int64
Geography Marks      int64
Computer Marks       int64
Attendance         float64
Hobbies             object
dtype: object

In [15]:
# Retrieve the columns (feature) names of the DataFrames 
stu_df.columns

Index(['Name', 'Age', 'City', 'Math Marks', 'Science Marks', 'English Marks',
       'History Marks', 'Geography Marks', 'Computer Marks', 'Attendance',
       'Hobbies'],
      dtype='object')

In [16]:
# Information about the DataFrame
stu_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             300 non-null    object
 1   Age              300 non-null    int64
 2   City             300 non-null    object
 3   Math Marks       300 non-null    int64
 4   Science Marks    300 non-null    int64
 5   English Marks    300 non-null    int64
 6   History Marks    300 non-null    int64
 7   Geography Marks  300 non-null    int64
 8   Computer Marks   300 non-null    int64
 9   Attendance       300 non-null    float64
 10  Hobbies          300 non-null    object
dtypes: float64(1), int64(7), object(3)
memory usage: 25.9+ KB

In [17]:
# Collecting Descriptive statistics of numerical data in a DataFrame. 
# It provides summary statistics such as count, mean, standard deviation, Min etc..
stu_df.describe()

,Age,Math Marks,Science Marks,English Marks,History Marks,Geography Marks,Computer Marks,Attendance
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,21.376667,78.383333,81.003333,80.826667,80.130000,80.393333,81.173333,85.274700
std,2.338021,12.325697,12.060743,11.444060,11.813762,11.562190,11.463332,8.749925
min,18.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,70.020000
25%,19.000000,66.750000,71.000000,71.000000,70.000000,71.000000,72.000000,77.465000
50%,21.000000,78.000000,82.000000,82.000000,80.000000,80.500000,82.000000,85.925000
75%,23.000000,90.000000,92.000000,90.000000,90.000000,91.000000,91.000000,92.877500
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,99.980000

In [18]:
# Transposing Rows & Columns 
stu_df.head(10).transpose()

,0,1,2,3,4,5,6,7,8,9
Name,Aarav_001,Aadhya_002,Vihaan_003,Anaya_004,Arjun_005,Diya_006,Ishaan_007,Myra_008,Kabir_009,Saanvi_010
Age,19,20,18,23,19,24,21,19,21,18
City,Hyderabad,Vijayawada,Visakhapatnam,Rajahmundry,Kakinada,Guntur,Bengaluru,Chennai,Pune,Mumbai
Math Marks,98,70,61,81,62,73,67,65,73,99
Science Marks,88,70,83,84,96,68,94,63,90,80
English Marks,74,83,89,86,66,85,73,88,74,75
History Marks,67,95,97,87,80,61,76,77,67,77
Geography Marks,80,99,61,75,68,79,95,85,73,83
Computer Marks,98,83,80,74,98,87,99,93,82,85
Attendance,74.68,70.62,79.13,72.72,98.47,90.5,79.35,96.84,71.36,78.43
Hobbies,Reading,Sports,Music,Drawing,Coding,Traveling,Photography,Gaming,Dancing,Gardening

<h2>RESULT</h2>
<h4>By using Pandas, DataFrames were successfully created from NumPy arrays and CSV files. Various DataFrame properties such as shape, column names, index, data types and statistical summaries were analyzed.</h4>

<h2>Conclusion</h2>

<h4>Thus, Pandas DataFrames were successfully created using NumPy arrays and an existing 
CSV dataset. Different DataFrame properties, rows, columns, indexes, and data values 
were analyzed. The experiment provided practical understanding of how Pandas can be 
used to organize and analyze structured data.</h4>