
<h2><center>DATA MANIPULATION WITH PANDAS</h2>


<h4>To perform data manipulation operations such as selecting, filtering, sorting, updating, and creating new columns using the Pandas
library on students dataset.</h4>

<h2> 1: Install and Import Pandas Library using commands:</h2>

In [2]:
import pandas as pd

<h2> 2: Load your new dataset</h2>

In [5]:
thrilokya_128 = pd.read_csv('employee_performance_dataset.csv')

In [ ]:
# Reading the head of the Dataset
thrilokya_128.head(5)

In [10]:
# Set Index for the DataFrame (unique identifier)
df = df.set_index('Employee_ID')

<h2> 3: Set Index and Check Dataset Information</h2>

In [ ]:
# Reading the head of the Dataset
thrilokya_128.head(5)

In [14]:
# Information about the DataFrame
thrilokya_128.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Employee_ID             100 non-null    int64
 1   Employee_Name           100 non-null    object
 2   Age                     100 non-null    int64
 3   Department              100 non-null    object
 4   City                    100 non-null    object
 5   Salary                  100 non-null    int64
 6   Experience_Years        100 non-null    int64
 7   Jan_Score               100 non-null    int64
 8   Feb_Score               100 non-null    int64
 9   Mar_Score               100 non-null    int64
 10  Apr_Score               100 non-null    int64
 11  May_Score               100 non-null    int64
 12  Jun_Score               100 non-null    int64
 13  Attendance              100 non-null    float64
 14  Current_Project         100 non-null    object
 15  Work_Mode               100 non-null    object
 16  Total_Score             100 non-null    int64
 17  Performance_Percentage  100 non-null    float64
dtypes: float64(2), int64(11), object(5)
memory usage: 14.2+ KB

<h2>4: Selecting Columns and Rows</h2>

In [15]:
# Selecting a single column
thrilokya_128['Employee_Name']

0        Aarav
1        Meera
2        Rohan
3        Anika
4        Kabir
        ...
95       Ira_4
96    Vihaan_4
97      Tara_4
98    Aditya_4
99     Nisha_4
Name: Employee_Name, Length: 100, dtype: object

In [16]:
# Selecting multiple columns
thrilokya_128[['Employee_Name', 'Department', 'City']].head(3)

  Employee_Name Department       City
0         Aarav         IT  Bengaluru
1         Meera         HR    Chennai
2         Rohan         HR     Mumbai

In [17]:
# Select row using position-based indexing
thrilokya_128.iloc[1]

Employee_ID                     5002
Employee_Name                  Meera
Age                               24
Department                        HR
City                         Chennai
Salary                         65118
Experience_Years                  10
Jan_Score                         96
Feb_Score                         89
Mar_Score                         81
Apr_Score                         69
May_Score                         83
Jun_Score                         92
Attendance                     78.57
Current_Project           Mobile App
Work_Mode                     Hybrid
Total_Score                      510
Performance_Percentage          85.0
Name: 1, dtype: object

In [23]:
# Select row using label-based indexing
thrilokya_128.loc[5003]

Employee_Name                      Rohan
Age                                   22
Department                            HR
City                              Mumbai
Salary                             54298
Experience_Years                       5
Jan_Score                             61
Feb_Score                             60
Mar_Score                             79
Apr_Score                             61
May_Score                             77
Jun_Score                             77
Attendance                         81.34
Current_Project           Data Migration
Work_Mode                         Remote
Total_Score                          415
Performance_Percentage             69.17
Name: 5003, dtype: object

<h2>5: Manipulating Data Based on Columns</h2>

In [24]:
thrilokya_128.head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.00,Website Revamp,Office,478,79.67
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.57,Mobile App,Hybrid,510,85.00

In [34]:
# Rounding Attendance to 2 decimal places
thrilokya_128['Attendance'] = thrilokya_128['Attendance'].round(1)

thrilokya_128.head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.67
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.00

<h2>6: Creating New Columns</h2>

In [35]:
# List of monthly performance columns
months_128 = [
    'Jan_Score',
    'Feb_Score',
    'Mar_Score',
    'Apr_Score',
    'May_Score',
    'Jun_Score'
]

In [37]:
# Calculate Total Score
thrilokya_128['Total_Score'] = thrilokya_128[months_128].sum(axis=1)

thrilokya_128.head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.67
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.00

In [39]:
# Calculate Performance Percentage
thrilokya_128['Performance_Percentage'] = ( thrilokya_128['Total_Score'] / 600) * 100

In [41]:
thrilokya_128.head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.666667
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.000000

In [44]:
# Round Performance Percentage to 2 decimal places
thrilokya_128['Performance_Percentage'] = (thrilokya_128['Performance_Percentage'].round(1))
thrilokya_128.head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.0

<h2>7: Conditional Filtering</h2>

In [45]:
# Employees with Attendance greater than 90%
thrilokya_128[thrilokya_128['Attendance'] > 90].head(5)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5004,Anika,30,IT,Delhi,67142,2,60,90,73,95,94,78,98.9,Cloud Upgrade,Remote,490,81.7
5006,Ira,33,HR,Pune,55283,4,98,96,59,93,95,65,92.4,Analytics,Remote,506,84.3
5007,Vihaan,29,HR,Delhi,56867,5,90,69,98,75,58,69,99.3,Analytics,Office,459,76.5
5008,Tara,32,Marketing,Bengaluru,36337,4,75,68,96,86,80,96,97.6,CRM Automation,Hybrid,501,83.5
5009,Aditya,26,Finance,Visakhapatnam,48162,12,92,82,92,80,78,69,90.1,Data Migration,Office,493,82.2

In [46]:
# Performance greater than 80% AND Attendance less than 90%
thrilokya_128[
    (thrilokya_128['Performance_Percentage'] > 80) &
    (thrilokya_128['Attendance'] < 90)
].head(5)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.0
5025,Neil,40,Operations,Hyderabad,72591,2,91,88,75,71,68,97,87.0,CRM Automation,Remote,490,81.7
5029,Rahul,39,HR,Bengaluru,50465,10,68,98,95,71,87,86,82.5,Data Migration,Hybrid,505,84.2
5035,Kabir_2,29,IT,Chennai,58113,6,72,77,96,87,80,98,84.0,Website Revamp,Remote,510,85.0
5037,Vihaan_2,38,IT,Mumbai,90949,10,82,55,88,89,98,97,82.1,Website Revamp,Office,509,84.8

In [48]:
# Employees from Hyderabad OR Chennai
thrilokya_128[(thrilokya_128['City'] == 'Hyderabad') |(thrilokya_128['City'] == 'Chennai')].head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.0
5013,Reyansh,38,Operations,Chennai,42016,6,88,55,93,75,86,56,94.4,CRM Automation,Office,453,75.5
5014,Diya,33,Finance,Chennai,35796,4,60,86,59,89,63,63,96.9,Website Revamp,Remote,420,70.0
5017,Yash,22,IT,Hyderabad,47003,2,59,87,70,72,97,86,97.5,Data Migration,Office,471,78.5
5023,Ritvik,31,HR,Hyderabad,69957,12,75,58,58,92,85,87,89.7,Analytics,Remote,455,75.8

In [50]:
# Employees who are 25 years old AND belong to IT
thrilokya_128[(thrilokya_128['Age'] == 25) & (thrilokya_128['Department'] == 'IT')]

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5027,Varun,25,IT,Kochi,45969,9,59,70,78,73,65,83,83.7,Data Migration,Remote,428,71.3

In [52]:
# Employees aged 25 OR 30 and belonging to IT
thrilokya_128[((thrilokya_128['Age'] == 25) |(thrilokya_128['Age'] == 30)) &(thrilokya_128['Department'] == 'IT')
]

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5004,Anika,30,IT,Delhi,67142,2,60,90,73,95,94,78,98.9,Cloud Upgrade,Remote,490,81.7
5027,Varun,25,IT,Kochi,45969,9,59,70,78,73,65,83,83.7,Data Migration,Remote,428,71.3
5081,Dev_3,30,IT,Bengaluru,79582,5,97,86,64,83,89,85,96.0,CRM Automation,Hybrid,504,84.0

<h2>8: Filtering Using .isin()</h2>

In [53]:
# Employees from multiple departments
thrilokya_128[thrilokya_128['Department'].isin(['IT', 'Finance', 'Marketing'])].head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5004,Anika,30,IT,Delhi,67142,2,60,90,73,95,94,78,98.9,Cloud Upgrade,Remote,490,81.7
5008,Tara,32,Marketing,Bengaluru,36337,4,75,68,96,86,80,96,97.6,CRM Automation,Hybrid,501,83.5
5009,Aditya,26,Finance,Visakhapatnam,48162,12,92,82,92,80,78,69,90.1,Data Migration,Office,493,82.2
5010,Nisha,38,Marketing,Vijayawada,81530,1,95,65,98,82,93,59,96.5,Mobile App,Hybrid,492,82.0

In [55]:
# Employees from multiple cities
thrilokya_128[thrilokya_128['City'].isin(['Hyderabad', 'Bengaluru', 'Pune'])].head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5006,Ira,33,HR,Pune,55283,4,98,96,59,93,95,65,92.4,Analytics,Remote,506,84.3
5008,Tara,32,Marketing,Bengaluru,36337,4,75,68,96,86,80,96,97.6,CRM Automation,Hybrid,501,83.5
5017,Yash,22,IT,Hyderabad,47003,2,59,87,70,72,97,86,97.5,Data Migration,Office,471,78.5
5023,Ritvik,31,HR,Hyderabad,69957,12,75,58,58,92,85,87,89.7,Analytics,Remote,455,75.8

In [56]:
# Employees with selected ages
thrilokya_128[thrilokya_128['Age'].isin([24, 25, 30])].head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7
5002,Meera,24,HR,Chennai,65118,10,96,89,81,69,83,92,78.6,Mobile App,Hybrid,510,85.0
5004,Anika,30,IT,Delhi,67142,2,60,90,73,95,94,78,98.9,Cloud Upgrade,Remote,490,81.7
5012,Kavya,25,Finance,Mumbai,42365,8,71,87,66,87,61,95,78.1,Analytics,Hybrid,467,77.8
5027,Varun,25,IT,Kochi,45969,9,59,70,78,73,65,83,83.7,Data Migration,Remote,428,71.3

<h2>9: Sorting the Table</h2>

In [58]:
# Sorting based on Age in descending order
thrilokya_128.sort_values('Age',ascending = False).head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5055,Neil_2,40,Sales,Mumbai,57995,12,95,70,61,74,98,93,82.3,CRM Automation,Office,491,81.8
5056,Shreya_2,40,IT,Pune,66913,7,87,96,76,55,81,86,92.2,Website Revamp,Office,481,80.2
5025,Neil,40,Operations,Hyderabad,72591,2,91,88,75,71,68,97,87.0,CRM Automation,Remote,490,81.7
5072,Kavya_3,40,Finance,Delhi,40149,8,80,72,87,89,86,83,92.8,Analytics,Office,497,82.8
5094,Anika_4,39,Finance,Kochi,64885,15,71,85,73,76,62,84,83.9,Mobile App,Office,451,75.2

In [59]:
# Sorting based on Salary in ascending order
thrilokya_128.sort_values('Salary',ascending=True).head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5028,Anvi,31,Operations,Kochi,32512,11,97,61,63,71,62,61,95.6,Data Migration,Remote,415,69.2
5093,Rohan_4,23,Finance,Delhi,34186,10,60,73,75,81,66,67,85.8,Mobile App,Office,422,70.3
5005,Kabir,28,Sales,Vijayawada,35003,11,60,69,61,79,72,84,82.9,Data Migration,Remote,425,70.8
5014,Diya,33,Finance,Chennai,35796,4,60,86,59,89,63,63,96.9,Website Revamp,Remote,420,70.0
5008,Tara,32,Marketing,Bengaluru,36337,4,75,68,96,86,80,96,97.6,CRM Automation,Hybrid,501,83.5

In [61]:
# Sorting based on Age and Performance Percentage
thrilokya_128.sort_values(['Age', 'Performance_Percentage'],ascending=False).head()

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5072,Kavya_3,40,Finance,Delhi,40149,8,80,72,87,89,86,83,92.8,Analytics,Office,497,82.8
5055,Neil_2,40,Sales,Mumbai,57995,12,95,70,61,74,98,93,82.3,CRM Automation,Office,491,81.8
5025,Neil,40,Operations,Hyderabad,72591,2,91,88,75,71,68,97,87.0,CRM Automation,Remote,490,81.7
5056,Shreya_2,40,IT,Pune,66913,7,87,96,76,55,81,86,92.2,Website Revamp,Office,481,80.2
5029,Rahul,39,HR,Bengaluru,50465,10,68,98,95,71,87,86,82.5,Data Migration,Hybrid,505,84.2

<h2>10: Updating Data</h2>

In [62]:
# Updating Hyderabad as HYD
thrilokya_128['City'] = thrilokya_128['City'].replace(['Hyderabad'],['HYD'])

In [63]:
thrilokya_128[thrilokya_128['City'] == 'HYD'].head(2)

,Employee_Name,Age,Department,City,Salary,Experience_Years,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance_Percentage
Employee_ID,,,,,,,,,,,,,,,,,
5017,Yash,22,IT,HYD,47003,2,59,87,70,72,97,86,97.5,Data Migration,Office,471,78.5
5023,Ritvik,31,HR,HYD,69957,12,75,58,58,92,85,87,89.7,Analytics,Remote,455,75.8

In [64]:
# Updating salary of Employee 5003
thrilokya_128.loc[5003, 'Salary'] = 60000

In [65]:
print(thrilokya_128.loc[5003, 'Salary'])

60000

<h2>11: Changing Column Names</h2>

In [66]:
# Changing column names
thrilokya_128 = thrilokya_128.rename(columns={
        'Employee_Name': 'Name',
        'Experience_Years': 'Experience',
        'Performance_Percentage': 'Performance'
    }
)

In [67]:
thrilokya_128.head(1)

,Name,Age,Department,City,Salary,Experience,Jan_Score,Feb_Score,Mar_Score,Apr_Score,May_Score,Jun_Score,Attendance,Current_Project,Work_Mode,Total_Score,Performance
Employee_ID,,,,,,,,,,,,,,,,,
5001,Aarav,25,IT,Bengaluru,48049,4,98,89,60,92,82,57,81.0,Website Revamp,Office,478,79.7

<h2> 12: Final Dataset</h2>

thrilokya_128

<h2>RESULT:</h2>
<h4>By using the Pandas library, various data manipulation techniques such as selecting specific rows and columns, rounding and updating values,
conditional filtering, renaming columns were successfully implemented on the student dataset.</h4>

<h2>Conclusion</h2>
<h4>Thus, various data manipulation operations were successfully performed using the 
Pandas library. Data was selected, filtered, sorted, updated, and new columns were 
created. The experiment demonstrated how Pandas can be used to efficiently manipulate 
and work with structured datasets.</h4>