<h2><center>DATA PRE-PROCESSING & FEATURE ENGINEERING</h2>

<h4>To implement data pre-processing and feature engineering techniques on a dataset including removing unnecessary features, feature
scaling and encoding categorical variables using Python libraries.</h4>

<h2>1: Import the basic libraries</h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

<h2>2: Load & Analyze the Dataset</h2>

In [2]:
thrilokya_128 = pd.read_csv('diabetes_risk_dataset.csv')

In [3]:
thrilokya_128.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         120 non-null    int64
 1   gender             120 non-null    object
 2   age                120 non-null    int64
 3   bmi                120 non-null    float64
 4   blood_pressure     120 non-null    int64
 5   glucose_level      120 non-null    float64
 6   insulin_level      120 non-null    float64
 7   family_history     120 non-null    object
 8   smoking_status     120 non-null    object
 9   physical_activity  120 non-null    object
 10  diet_type          120 non-null    object
 11  residence_type     120 non-null    object
 12  diabetes           120 non-null    int64
dtypes: float64(3), int64(4), object(6)
memory usage: 12.3+ KB

In [4]:
thrilokya_128.head()

,patient_id,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,smoking_status,physical_activity,diet_type,residence_type,diabetes
0,2001,Male,32,37.7,136,219.8,126.6,Yes,Former,High,Moderate,Rural,1
1,2002,Female,55,27.7,132,192.9,176.4,No,Current,High,Moderate,Urban,1
2,2003,Male,56,31.9,116,171.3,246.3,No,Former,High,Moderate,Rural,1
3,2004,Female,73,35.7,130,120.8,99.9,No,Current,Moderate,Unhealthy,Urban,0
4,2005,Female,58,22.2,146,172.2,249.0,No,Never,Moderate,Unhealthy,Rural,0

In [5]:
thrilokya_128.shape

(120, 13)

In [15]:
# Check for any Null Values
thrilokya_128.isnull().sum()

gender               0
age                  0
bmi                  0
blood_pressure       0
glucose_level        0
insulin_level        0
family_history       0
smoking_status       0
physical_activity    0
diet_type            0
residence_type       0
diabetes             0
dtype: int64

<h2> 3: Remove Unnecessary Features</h2>

In [7]:
# Removing patient_id column, since it does not add predictive value
thrilokya_128 = thrilokya_128.drop('patient_id', axis=1)

In [8]:
thrilokya_128.shape

(120, 12)

<h2> 4: Scale the Numerical Features</h2>

In [9]:
thrilokya_128.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             120 non-null    object
 1   age                120 non-null    int64
 2   bmi                120 non-null    float64
 3   blood_pressure     120 non-null    int64
 4   glucose_level      120 non-null    float64
 5   insulin_level      120 non-null    float64
 6   family_history     120 non-null    object
 7   smoking_status     120 non-null    object
 8   physical_activity  120 non-null    object
 9   diet_type          120 non-null    object
 10  residence_type     120 non-null    object
 11  diabetes           120 non-null    int64
dtypes: float64(3), int64(3), object(6)
memory usage: 11.4+ KB

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
z_scaler = StandardScaler()

In [12]:
thrilokya_128[['age', 'blood_pressure', 'insulin_level']] = z_scaler.fit_transform(
    thrilokya_128[['age', 'blood_pressure', 'insulin_level']]
)

In [13]:
thrilokya_128.head(3)

,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,smoking_status,physical_activity,diet_type,residence_type,diabetes
0,Male,-1.155223,37.7,0.402995,219.8,-0.092499,Yes,Former,High,Moderate,Rural,1
1,Female,0.270723,27.7,0.195888,192.9,0.726672,No,Current,High,Moderate,Urban,1
2,Male,0.332721,31.9,-0.632538,171.3,1.876473,No,Former,High,Moderate,Rural,1

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mm_scaler = MinMaxScaler()

In [17]:
thrilokya_128[['bmi', 'glucose_level']] = mm_scaler.fit_transform(
    thrilokya_128[['bmi', 'glucose_level']]
)

In [18]:
thrilokya_128.head(3)

,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,smoking_status,physical_activity,diet_type,residence_type,diabetes
0,Male,-1.155223,0.913462,0.402995,1.000000,-0.092499,Yes,Former,High,Moderate,Rural,1
1,Female,0.270723,0.432692,0.195888,0.819826,0.726672,No,Current,High,Moderate,Urban,1
2,Male,0.332721,0.634615,-0.632538,0.675151,1.876473,No,Former,High,Moderate,Rural,1

<h2> 5: Encode the Categorical Features</h2>

In [30]:
from sklearn.preprocessing import LabelEncoder
# Create an Instance
encoder = LabelEncoder()

In [21]:
thrilokya_128['gender'] = encoder.fit_transform(thrilokya_128['gender'])

thrilokya_128['family_history'] = encoder.fit_transform(thrilokya_128['family_history'])

In [22]:
thrilokya_128.head(3)

,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,smoking_status,physical_activity,diet_type,residence_type,diabetes
0,1,-1.155223,0.913462,0.402995,1.000000,-0.092499,1,Former,High,Moderate,Rural,1
1,0,0.270723,0.432692,0.195888,0.819826,0.726672,0,Current,High,Moderate,Urban,1
2,1,0.332721,0.634615,-0.632538,0.675151,1.876473,0,Former,High,Moderate,Rural,1

In [37]:
pd.get_dummies(thrilokya_128)

,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,diabetes,smoking_status_Former,smoking_status_Never,physical_activity_Low,physical_activity_Moderate,diet_type_Moderate,diet_type_Unhealthy,residence_type_Urban
0,1,-1.155223,0.913462,0.402995,1.000000,-0.092499,1,1,True,False,False,False,True,False,False
1,0,0.270723,0.432692,0.195888,0.819826,0.726672,0,1,False,False,False,False,True,False,True
2,1,0.332721,0.634615,-0.632538,0.675151,1.876473,0,1,True,False,False,False,True,False,False
3,0,1.386680,0.817308,0.092335,0.336906,-0.531694,0,0,False,False,False,True,False,True,True
4,0,0.456716,0.168269,0.920762,0.681179,1.920886,0,0,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1,0.022732,0.230769,0.558325,0.768922,-1.102482,0,1,False,False,False,True,False,True,True
116,0,0.518714,0.495192,0.765432,0.703282,-0.742244,1,0,True,False,False,True,True,False,False
117,1,1.138690,0.692308,-1.046752,0.137307,1.552423,0,0,False,False,False,True,False,True,True
118,0,-0.225258,0.259615,-1.409188,0.767582,-0.344173,1,0,False,True,False,True,False,True,True
119,1,1.448678,0.966346,1.334975,0.176825,-0.992272,0,0,False,True,False,False,False,True,True

<h3>Apply One Hot Encoding using pd.get_dummies()</h3>

In [43]:
pd.get_dummies(thrilokya_128)

,gender,age,bmi,blood_pressure,glucose_level,insulin_level,family_history,diabetes,smoking_status_Former,smoking_status_Never,physical_activity_Low,physical_activity_Moderate,diet_type_Moderate,diet_type_Unhealthy,residence_type_Urban
0,1,-1.155223,0.913462,0.402995,1.000000,-0.092499,1,1,1,0,0,0,1,0,0
1,0,0.270723,0.432692,0.195888,0.819826,0.726672,0,1,0,0,0,0,1,0,1
2,1,0.332721,0.634615,-0.632538,0.675151,1.876473,0,1,1,0,0,0,1,0,0
3,0,1.386680,0.817308,0.092335,0.336906,-0.531694,0,0,0,0,0,1,0,1,1
4,0,0.456716,0.168269,0.920762,0.681179,1.920886,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1,0.022732,0.230769,0.558325,0.768922,-1.102482,0,1,0,0,0,1,0,1,1
116,0,0.518714,0.495192,0.765432,0.703282,-0.742244,1,0,1,0,0,1,1,0,0
117,1,1.138690,0.692308,-1.046752,0.137307,1.552423,0,0,0,0,0,1,0,1,1
118,0,-0.225258,0.259615,-1.409188,0.767582,-0.344173,1,0,0,1,0,1,0,1,1
119,1,1.448678,0.966346,1.334975,0.176825,-0.992272,0,0,0,1,0,0,0,1,1

In [46]:
# Find Boolean columns
bool_col = thrilokya_128.select_dtypes(include='bool').columns

# Convert Boolean columns into integers
for col in bool_col:
    thrilokya_128[col] = thrilokya_128[col].astype(int)

thrilokya_128.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   gender                      120 non-null    int64
 1   age                         120 non-null    float64
 2   bmi                         120 non-null    float64
 3   blood_pressure              120 non-null    float64
 4   glucose_level               120 non-null    float64
 5   insulin_level               120 non-null    float64
 6   family_history              120 non-null    int64
 7   diabetes                    120 non-null    int64
 8   smoking_status_Former       120 non-null    int64
 9   smoking_status_Never        120 non-null    int64
 10  physical_activity_Low       120 non-null    int64
 11  physical_activity_Moderate  120 non-null    int64
 12  diet_type_Moderate          120 non-null    int64
 13  diet_type_Unhealthy         120 non-null    int64
 14  residence_type_Urban        120 non-null    int64
dtypes: float64(5), int64(10)
memory usage: 14.2 KB

In [48]:
# Processed Dataset
thrilokya_128.shape

(120, 15)

In [49]:
# Save Processed Dataset if necessary
thrilokya_128.to_csv('processed_dataset.csv', index=False)

<h2>RESULT:</h2>
<h4>The dataset was pre-processed by removing unnecessary features, scaling numerical columns using StandardScaler and MinMaxScaler,
and encoding categorical variables using Label Encoding and One-Hot Encoding. The dataset is now transformed into a clean numerical
form, ready for use in machine learning models.
</h4>

<h2>Conclusion</h2>
<h4>Thus, data preprocessing and feature engineering techniques were successfully 
implemented on the dataset. Unnecessary features were removed, numerical features 
were scaled, and categorical variables were prepared for further analysis. The 
experiment demonstrated how preprocessing and feature engineering can improve the 
quality and suitability of data for machine learning applications.</h4>